### ISSUE TITLE
Add `sortSmallArrayBy`

### ISSUE THREAD

**Issue by konsumlamm** [meooow25/samsort#14]
It would be nice to have a variant that works on `SmallArray#`s.

My use case is that I want to use this to implement sorting for my [rrb-vector](https://github.com/konsumlamm/rrb-vector) library, which uses `SmallArray`s (the benchmarks are very promising).

**Comment by meooow25** [comment]
Sounds like a good use case, though I don't see how sorting a `SmallArray` would help. For rrb-vector, isn't the data spread across multiple `SmallArray`s?

In general, the idea with this library is to copy the data into a `MutableArray#` (if it's not already in one), sort it, and copy it back out. I have used it in a similar case, sorting a sequence, which could be likely be adapted for rrb-vector with small changes:

https://github.com/meooow25/seqn/blob/775acc81790377153c5236e5403363abd7af1606/src/Data/Seqn/Internal/Seq.hs#L1235-L1241

**Comment by konsumlamm** [comment]
> Sounds like a good use case, though I don't see how sorting a `SmallArray` would help. For rrb-vector, isn't the data spread across multiple `SmallArray`s?

The arrays I use are actually slices of `SmallArray`s. My idea is to build the tree out of adjacent slices of the sorted array, to avoid copying.
The disadvantage of this approach is that the whole array is kept around, even if only a small part of it is still used.

**Comment by meooow25** [comment]
> My idea is to build the tree out of adjacent slices of the sorted array, to avoid copying.

Oh interesting...

> The disadvantage of this approach is that the whole array is kept around, even if only a small part of it is still used.

Yes, I'm not sure this pays off, only to avoid one batch of copying. I imagine it is also worse for GC if a `SmallArray#` is actually huge.

---

Back to the issue, I'm reluctant to add this because a `SmallArray#` is typically, well, small. [Data.Primitive.SmallArray](https://hackage.haskell.org/package/primitive-0.9.0.0/docs/Data-Primitive-SmallArray.html) says

> The card size is 128, so for uses much larger than that, Array would likely be superior.

At these sizes, insertion sort may be fast enough to not require more complex algorithms.

**Comment by konsumlamm** [comment]
Yeah, you're probably right.
